INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(1, 'Железный человек', 8.6, 157654);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(2, 'Интерстеллар', 8.9, 186754);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(3, 'Омерзительная восьмёрка', 8.5, 116814);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(4, 'Бойцовский клуб', 8.8, 186699);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(5, 'Тёмный рыцарь', 8.7, 212204);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(6, 'Брат', 8.5, 94587);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(7, 'Волк с Уолл-стрит', 8.4, 236547);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(8, 'Игры разума', 8.2, 32732);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(9, 'Американская история X', 8.3, 20441);
INSERT INTO Medialibrary."Movie Library" (movie_id, name, rating, number_of_raitings) VALUES(10, 'Драйв', 7.3, 388888);
